import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/navigation/header/Header";
import Providers from "@/components/Providers";
import MobileNav from "@/components/navigation/MobilNav";
import SideMenu from "@/components/navigation/SideNav";
// import Head from 'next/head'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};

export default function RootLayout({ children, }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <Head children={undefined}>
      </Head> */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>

          <div className="min-h-screen bg-base-100 text-base-content">
            <header className="">
              <Header />
            </header>
            <div className="flex min-h-screen">
              <div className="hidden md:flex ">
                <SideMenu />
              </div>
              <main className="w-full z-0">
                <div className="lg:block z-0">
        {children}
                </div>
              </main>
            </div>
            <div className="block md:hidden">
              <MobileNav />
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}

